// Fake seed data for the 同窗 click-thru
window.STUDENTS = [
  {
    id: 's1',
    name: '林安',
    age: 21,
    pronoun: '她',
    school: '北京大学',
    major: '中文系',
    year: '大三',
    city: '北京',
    photo: '../../assets/placeholders/portrait-01.png',
    tagline: '喜欢在图书馆三楼靠窗的位置看书。',
    bio: '在北大中文系读大三。喜欢 19 世纪的英国小说和木心的散文。最近在重读《人间词话》，会做笔记。\n\n周末通常在五道口的咖啡店改毕业论文，或者去未名湖散步。不太擅长发朋友圈，但是会写很长的日记。',
    interests: [
      { label: '阅读', cat: 'sage' },
      { label: '钢琴', cat: 'plum' },
      { label: '徒步', cat: 'sage' },
      { label: '咖啡', cat: 'honey' },
    ],
    looking: '想认识一个能一起安静读书、偶尔讨论几句的人。不一定要相同专业。',
    verified: true,
  },
  {
    id: 's2',
    name: '陈思远',
    age: 23,
    pronoun: '他',
    school: '清华大学',
    major: '建筑学',
    year: '研一',
    city: '北京',
    photo: '../../assets/placeholders/portrait-04.png',
    tagline: '周末喜欢在城市里漫无目的地走。',
    bio: '清华建筑学研一。本科在同济。\n\n业余时间在做城市观察的摄影项目，已经走了北京、上海、苏州、京都。喜欢扫街，胶片机和数码都用。',
    interests: [
      { label: '摄影', cat: 'plum' },
      { label: '骑行', cat: 'sage' },
      { label: '咖啡', cat: 'honey' },
      { label: '电影', cat: 'plum' },
    ],
    looking: '希望对方有自己稳定在做的事。我不太聊天，但是写信可以写很长。',
    verified: true,
  },
  {
    id: 's3',
    name: '苏沐',
    age: 22,
    pronoun: '她',
    school: '复旦大学',
    major: '新闻学',
    year: '大四',
    city: '上海',
    photo: '../../assets/placeholders/portrait-02.png',
    tagline: '最近在学冲泡手冲咖啡。',
    bio: '复旦新闻学大四，明年去哥伦比亚读研。\n\n在《澎湃》实习过半年。爱好是手冲咖啡，最近在练 V60。家里养了一只叫芋圆的橘猫。',
    interests: [
      { label: '咖啡', cat: 'honey' },
      { label: '猫', cat: 'plum' },
      { label: '写作', cat: 'sky' },
      { label: '骑行', cat: 'sage' },
    ],
    looking: '想认识一个对世界保持好奇心的人。能一起做计划，也能一起放空。',
    verified: true,
  },
  {
    id: 's4',
    name: '程书宁',
    age: 24,
    pronoun: '她',
    school: '浙江大学',
    major: '生物医学工程',
    year: '研二',
    city: '杭州',
    photo: '../../assets/placeholders/portrait-05.png',
    tagline: '在实验室一坐就是一天。',
    bio: '浙大生物医学工程研二。\n\n白天在实验室，晚上在球场。打了十年羽毛球，校队队长。读 Murakami，听爵士，写代码。',
    interests: [
      { label: '羽毛球', cat: 'sage' },
      { label: '爵士', cat: 'plum' },
      { label: '编程', cat: 'sky' },
      { label: '旅行', cat: 'sage' },
    ],
    looking: '比起一见钟情，我更相信一起经历过一些事之后的喜欢。',
    verified: true,
  },
  {
    id: 's5',
    name: '何砚',
    age: 22,
    pronoun: '他',
    school: '南京大学',
    major: '哲学系',
    year: '大四',
    city: '南京',
    photo: '../../assets/placeholders/portrait-03.png',
    tagline: '正在写本科论文，主题是维特根斯坦。',
    bio: '南大哲学系大四。\n\n准备申请欧洲的硕士。爱好是辩论和爬山。会写一点书法。',
    interests: [
      { label: '辩论', cat: 'sky' },
      { label: '登山', cat: 'sage' },
      { label: '书法', cat: 'plum' },
    ],
    looking: '愿意聊一些没有答案的问题的人。',
    verified: false,
  },
  {
    id: 's6',
    name: '宋知夏',
    age: 23,
    pronoun: '她',
    school: '中央美术学院',
    major: '版画系',
    year: '研一',
    city: '北京',
    photo: '../../assets/placeholders/portrait-06.png',
    tagline: '在工作室刻版画到深夜的人。',
    bio: '央美版画系研一。\n\n做铜版和木刻。每年办一两次小型展。喜欢做饭，尤其是江浙菜。',
    interests: [
      { label: '版画', cat: 'plum' },
      { label: '做饭', cat: 'honey' },
      { label: '猫', cat: 'plum' },
      { label: '电影', cat: 'plum' },
    ],
    looking: '想找一个生活里有具体的事可以做的人，不要悬浮。',
    verified: true,
  },
];

window.MESSAGES = {
  s2: [
    { from: 'them', text: '你好。我看了你的资料 — 我也很喜欢《人间词话》的"境界"那一节。', t: '昨天 21:14' },
    { from: 'me',   text: '是吗。你最喜欢哪一句？', t: '昨天 21:20' },
    { from: 'them', text: '"昨夜西风凋碧树。独上高楼，望尽天涯路。" — 大概因为我现在在写毕设。', t: '昨天 21:23' },
    { from: 'me',   text: '哈哈，那是第一境。第二第三呢？', t: '昨天 21:25' },
  ],
  s3: [
    { from: 'them', text: '看到你也喜欢手冲。你用什么豆子？', t: '今天 10:02' },
  ],
};
